### ISSUE TITLE
remember_device on logout

### ISSUE THREAD

**Issue by GeekOnCoffee** [twilio/authy-devise#163]
When I log out and log back in, it is forcing me to auth again; is that an issue with my implementation (we've got a bit of an unusual devise setup), or is that working as intended?

**Comment by philnash** [comment]
It's been a while since I've been in the code for this project, but after a quick look around I don't believe this plugin touches the sign out process and leaves it all to devise. That resets the session, but leaves cookies in place.

I just tested this in [the example app](https://github.com/twilio/authy-devise-demo/) and the `remember_device` cookie did remain after sign out.

Does your app/devise setup do things with cookies during sign out?

**Comment by GeekOnCoffee** [comment]
Interestingly the cookie is there, but the session variable isn't getting set; I think that gives me enough to go on, thanks!

**Comment by philnash** [comment]
Remembering the device shouldn't require anything in the session, it's a signed cookie. You can see what it's checking for here: https://github.com/twilio/authy-devise/blob/4d2ee10bac9a265d6c907e6295b3c5e7688ffd81/lib/devise-authy/controllers/helpers.rb#L25-L36.

**Comment by GeekOnCoffee** [comment]
Correct, but my custom code was looking for the session variable

**Comment by philnash** [comment]
Ok, as long as you know what you're looking for now! Let me know if there's anything else I can help with.
